monitor_queue_sizes:
  cron: "* * * * * America/New_York"
  class: "MonitorJob"
  queue: monitor
  args:
    - "Monitoring::QueueSizeCheck"
  description: "Send queue sizes to Librato"
monitor_queue_sizes_aws:
  cron: "*/5 * * * * * America/New_York"
  class: "MonitorJob"
  queue: monitor
  args:
    - "Monitoring::QueueSizeCheck"
    - "Monitoring::AwsNotifier"
    - namespace: "StitchFix/iZombie"
      metric_name: "iz-job-queue-depth"
  description: "Send queue sizes to Cloudwatch"
monitor_queue_sizes_statsd:
  cron: "* * * * * America/New_York"
  class: "MonitorJob"
  queue: monitor
  args:
    - "Monitoring::QueueSizeCheck"
    - "Monitoring::StatsdNotifier"
  description: "Send queue sizes to statsd"
monitor_failed:
  cron: "* * * * * America/New_York"
  class: "MonitorJob"
  queue: monitor
  args:
    - "Monitoring::FailedJobCheck"
  description: "Send failed job counts to Librato"
monitor_failed_statsd:
  cron: "* * * * * America/New_York"
  class: "MonitorJob"
  queue: monitor
  args:
    - "Monitoring::FailedJobCheck"
    - "Monitoring::StatsdNotifier"
  description: "Send failed job counts to Statsd"
monitor_stale_workers:
  cron: "* * * * * America/New_York"
  class: "MonitorJob"
  queue: monitor
  args:
    - "Monitoring::StaleWorkerCheck"
    - "Monitoring::LibratoNotifier"
    - type: "measure"
      unit: "workers"
  description: "Send stale worker counts to Librato"
monitor_failed_by_class:
  cron: "* * * * * America/New_York"
  class: "MonitorJob"
  queue: monitor
  args:
    - "Monitoring::FailedJobByClassCheck"
  description: "Send failed job counts by class to Librato"
kill_stale_workers:
  # Every hour on the 8's
  cron: "8 * * * * America/New_York"
  class: "Resqutils::StaleWorkersKiller"
  queue: worker_killer_job
  description: "Kills any stale workers"
